sql.select_customer=databasePRUE; SELECT FIRST_NAME, LAST_NAME, CUSTOMER_ID, NATIONALITY_ID, GENDER_ID, IDENTITY_DOCUMENT, IDENTITY_DOCUMENT_NUMBER, IDENTITY_DOCUMENT_TYPE_ID FROM T_PRUE_CUSTOMER WHERE IDENTITY_DOCUMENT_TYPE_ID = ? AND IDENTITY_DOCUMENT_NUMBER = ?
databasePRUE.url=jdbc:postgresql://localhost:5432/prue_customers
databasePRUE.username=postgres
databasePRUE.password=Diegoarc8
databasePRUE.driver=org.postgresql.Driver